- name: INSTALLAING {{APPNAME}}
  dnf:
    name: ngnix
    state: present

- name: CREATE BACKUP FOLDER FOR OLD HTML CONTENT
  file:
    path: "/tmp/BACK_UP_{{ansible_date_time.iso8601}}"
    state: directory
  register: backup_folder

- name: showing backup_folder 
  debug:
    msg: "BACKUP_FOLDER: {{backup_folder}}"


