
- name: INSTALLING {{APPNAME}}
  dnf:
    name: nginx
    state: present

- name: Calculate IST timestamp
  command: date +'%Y-%m-%d_%H-%M-%S' --date='TZ="Asia/Kolkata"'

  register: ist_timestamp

- name: CREATE BACKUP FOLDER FOR OLD HTML CONTENT
  file:
    path: "/tmp/BACK_UP_{{ ist_timestamp.stdout }}"
    state: directory
  register: backup_folder

- name: SHOWING BACKUP FOLDER 
  debug:
    msg: "BACKUP_FOLDER: {{ backup_folder }}"

- name: COPY THE HTML CONTENT INTO BACKUP FOLDER
  copy:
    src: "/usr/share/nginx/html"
    dest: "/tmp/BACK_UP_{{ ist_timestamp.stdout }}"
    remote_src: yes
